// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cperson struct {
	ID        int    `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Gender    string `json:"gender"`
	CarID     int    `json:"car_id"`
}

type Iperson struct {
	ID       int    `json:"id"`
	FullName string `json:"full_name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Operson struct {
	Details string `json:"details"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Getdata struct {
	First *int `json:"first"`
	After *int `json:"after"`
}

type Loginip struct {
	EmailID string `json:"email_id"`
	Pasword string `json:"pasword"`
}

type Loginop struct {
	EmailID  string `json:"email_id"`
	Username string `json:"username"`
	PhoneNo  string `json:"phone_no"`
}

type Outperson struct {
	Getperson string `json:"getperson"`
}

type Userop struct {
	Userreg string `json:"userreg"`
}

type Userregistration struct {
	EmailID  string `json:"email_id"`
	Username string `json:"username"`
	Pasword  string `json:"pasword"`
	PhoneNo  string `json:"phone_no"`
}
